# This is an example of back-filling day for a daily cron workflow.
# See ../docs/cron-backfill.md
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: job
  namespace: argo
spec:
  entrypoint: main
  arguments:
    parameters:
      - name: date
        # use "yesterday" is a magic value to tell the script it needs to determine the day to run
        value: yesterday
  templates:
    - name: main
      inputs:
        parameters:
          - name: date
      script:
        image: busybox
        command:
          - sh
        source: |
          date="{{inputs.parameters.date}}"
          if [ $date = yesterday ]; then
            date=$(date -d yesterday +%Y-%m-%d)
          fi
          echo "run for $date"
---
apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: daily-job
  namespace: argo
spec:
  # run daily at 2am
  schedules:
    - "0 2 * * *"
  workflowSpec:
    workflowTemplateRef:
      name: job